**Learning Pandas**

https://numpy.org/doc/stable/user/absolute_beginners.html

In [1]:
import numpy as np

**Array Fundamentals**

In [6]:
# Innit np array

a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [11]:
# Accessing element

a[0]

np.int32(1)

In [13]:
# Mutability = True
a[0] = 10
a[0]

np.int32(10)

In [16]:
# Slicing
a[:3]

array([10,  2,  3])

In [22]:
# Python lists create a copy when slicing while 
# numPy arrays creates a view (an object that refers to the data in the original array)

lis = [1,2, 3]
arr = np.array([1,2, 3])
print(lis, arr)

lis_sliced = lis[:2]
arr_sliced = arr[:2]
print(lis_sliced, arr_sliced)

lis_sliced[0] = 10
arr_sliced[0] = 10
print(lis_sliced, arr_sliced)

print(lis, arr)
# Printing after updating the sliced array causes teh original array to change)

[1, 2, 3] [1 2 3]
[1, 2] [1 2]
[10, 2] [10  2]
[1, 2, 3] [10  2  3]


In [24]:
#  Innitialising 2 and higher dimensional arrays

a = np.array([[1,2,3], [4,5,6], [7,8,9]]) # A 2 dimensional array
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
# Accessing element of higher dimensionality arrays

a[2, 1] # Row x Column

np.int32(8)

**Array Attributes**

This section covers the ndim, shape, size, and dtype attributes of an array.

In [30]:
# Dimesnions and Shape of array

print(a.ndim)
print(a.shape)
print(len(a.shape) == a.ndim)

2
(3, 3)
True


In [32]:
# Total amount of elements

a.size

9

In [33]:
#  Arrays are generally HOMOGENEOUS (contain elements of only one data type)
# Data type of the array

a.dtype

dtype('int32')

**Creating a basic array**

This section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

In [37]:
# Creating an array filled with 0's
print(np.zeros(2))

# Creating an array filled with 1's
print(np.ones(2))

[0. 0.]
[1. 1.]


In [39]:
# Creating an "empty" array (initial content is random and depends on the state of the memory)
# empty() > zeros() and other similar funcs for speed

np.empty(2)

array([1., 1.])

In [41]:
# Create an array with a range of values
print(np.arange(4))

# arange is customisable
print(np.arange(0, 10, 3))

[0 1 2 3]
[0 3 6 9]


In [43]:
# Create an array with linearly spaced values

np.linspace(0, 8, num=5)

array([0., 2., 4., 6., 8.])

In [47]:
# Specify data type of array as defualt is np.float64

x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

**Adding, removing, and sorting elements**

This section covers np.sort(), np.concatenate()

In [50]:
# Sorting with arrays

# Sorting with sort() - Returns a sorted copy of the passed in array
arr = np.array([2,6,1,4,8,3,2])
print(arr)
print(np.sort(arr))

# argsort - which is an indirect sort along a specified axis,

# lexsort - which is an indirect stable sort on multiple keys,

# searchsorted - which will find elements in a sorted array, and

# partition - which is a partial sort.


[2 6 1 4 8 3 2]
[1 2 2 3 4 6 8]


In [62]:
# Concatinating arrays

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(np.concatenate((a, b)))

# Concatinating based on axis
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(np.concatenate((a, b), axis=0))

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]]


In [63]:
#  To remove elements from an array use indexing to select elements that are needed to be kept

**Reshaping an array**

This section covers arr.reshape()

In [66]:
# Reshaping an array to change dimensions of it

a = np.arange(8)
print(a)
b = a.reshape(4, 2)
print(a.reshape(4, 2))
print(a.reshape(2, 4))

[0 1 2 3 4 5 6 7]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 2 3]
 [4 5 6 7]]


**How to convert a 1D array into a 2D array (how to add a new axis to an array)**

This section covers np.newaxis, np.expand_dims

In [77]:
# np.newaxis to increase dimension by one

a = np.array([1,2,3,4])
print(a, a.shape)

print(a[np.newaxis, :], a[np.newaxis, :].shape)

print(a[:, np.newaxis], a[:, np.newaxis].shape)

[1 2 3 4] (4,)
[[1 2 3 4]] (1, 4)
[[1]
 [2]
 [3]
 [4]] (4, 1)


In [87]:
# np.expand_dims to expand array by inserting a new axis at a speicfied position

a = np.array([1,2,3,4])
print(a, a.shape)

print(np.expand_dims(a, axis=0), np.expand_dims(a, axis=0).shape)
print(np.expand_dims(a, axis=1), np.expand_dims(a, axis=1).shape)

[1 2 3 4] (4,)
[[1 2 3 4]] (1, 4)
[[1]
 [2]
 [3]
 [4]] (4, 1)


**Indexing and slicing**

In [90]:
# Slicing

arr = np.array([1,2,3,4])

print(arr[:2])
print(arr[2:])
print(arr[1:3])
print(arr[:-1])

[1 2]
[3 4]
[2 3]
[1 2 3]


In [107]:
# Selecting values from array taht fulfill certain conditions

arr = np.arange(1, 13).reshape(3, 4)
print(arr)
print()

# Create a boolean mask to select certain values
print(arr > 6)
print()

print(arr[arr > 6])
print()

# And operations can be done with the & operator
print(arr[(arr>2) & (arr<10)])
print()

# Or operations can be done with the | operator
print(arr[(arr<5) | (arr==10)])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]

[ 7  8  9 10 11 12]

[3 4 5 6 7 8 9]

[ 1  2  3  4 10]
