**Learning NumPy**

https://numpy.org/doc/stable/user/absolute_beginners.html

In [3]:
import numpy as np

**Array Fundamentals**

In [ ]:
# Innit np array

a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
# Accessing element

a[0]

np.int32(1)

In [ ]:
# Mutability = True
a[0] = 10
a[0]

np.int32(10)

In [ ]:
# Slicing
a[:3]

array([10,  2,  3])

In [ ]:
# Python lists create a copy when slicing while 
# numPy arrays creates a view (an object that refers to the data in the original array)

lis = [1,2, 3]
arr = np.array([1,2, 3])
print(lis, arr)

lis_sliced = lis[:2]
arr_sliced = arr[:2]
print(lis_sliced, arr_sliced)

lis_sliced[0] = 10
arr_sliced[0] = 10
print(lis_sliced, arr_sliced)

print(lis, arr)
# Printing after updating the sliced array causes teh original array to change)

[1, 2, 3] [1 2 3]
[1, 2] [1 2]
[10, 2] [10  2]
[1, 2, 3] [10  2  3]


In [ ]:
#  Innitialising 2 and higher dimensional arrays

a = np.array([[1,2,3], [4,5,6], [7,8,9]]) # A 2 dimensional array
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Accessing element of higher dimensionality arrays

a[2, 1] # Row x Column

np.int32(8)

**Array Attributes**

This section covers the ndim, shape, size, and dtype attributes of an array.

In [ ]:
# Dimesnions and Shape of array

print(a.ndim)
print(a.shape)
print(len(a.shape) == a.ndim)

2
(3, 3)
True


In [ ]:
# Total amount of elements

a.size

9

In [ ]:
#  Arrays are generally HOMOGENEOUS (contain elements of only one data type)
# Data type of the array

a.dtype

dtype('int32')

**Creating a basic array**

This section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

In [ ]:
# Creating an array filled with 0's
print(np.zeros(2))

# Creating an array filled with 1's
print(np.ones(2))

[0. 0.]
[1. 1.]


In [ ]:
# Creating an "empty" array (initial content is random and depends on the state of the memory)
# empty() > zeros() and other similar funcs for speed

np.empty(2)

array([1., 1.])

In [ ]:
# Create an array with a range of values
print(np.arange(4))

# arange is customisable
print(np.arange(0, 10, 3))

[0 1 2 3]
[0 3 6 9]


In [ ]:
# Create an array with linearly spaced values

np.linspace(0, 8, num=5)

array([0., 2., 4., 6., 8.])

In [ ]:
# Specify data type of array as defualt is np.float64

x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

**Adding, removing, and sorting elements**

This section covers np.sort(), np.concatenate()

In [ ]:
# Sorting with arrays

# Sorting with sort() - Returns a sorted copy of the passed in array
arr = np.array([2,6,1,4,8,3,2])
print(arr)
print(np.sort(arr))

# argsort - which is an indirect sort along a specified axis,

# lexsort - which is an indirect stable sort on multiple keys,

# searchsorted - which will find elements in a sorted array, and

# partition - which is a partial sort.


[2 6 1 4 8 3 2]
[1 2 2 3 4 6 8]


In [ ]:
# Concatinating arrays

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(np.concatenate((a, b)))

# Concatinating based on axis
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(np.concatenate((a, b), axis=0))

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#  To remove elements from an array use indexing to select elements that are needed to be kept

**Reshaping an array**

This section covers arr.reshape()

In [ ]:
# Reshaping an array to change dimensions of it

a = np.arange(8)
print(a)
b = a.reshape(4, 2)
print(a.reshape(4, 2))
print(a.reshape(2, 4))

[0 1 2 3 4 5 6 7]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 2 3]
 [4 5 6 7]]


**How to convert a 1D array into a 2D array (how to add a new axis to an array)**

This section covers np.newaxis, np.expand_dims

In [ ]:
# np.newaxis to increase dimension by one

a = np.array([1,2,3,4])
print(a, a.shape)

print(a[np.newaxis, :], a[np.newaxis, :].shape)

print(a[:, np.newaxis], a[:, np.newaxis].shape)

[1 2 3 4] (4,)
[[1 2 3 4]] (1, 4)
[[1]
 [2]
 [3]
 [4]] (4, 1)


In [ ]:
# np.expand_dims to expand array by inserting a new axis at a speicfied position

a = np.array([1,2,3,4])
print(a, a.shape)

print(np.expand_dims(a, axis=0), np.expand_dims(a, axis=0).shape)
print(np.expand_dims(a, axis=1), np.expand_dims(a, axis=1).shape)

[1 2 3 4] (4,)
[[1 2 3 4]] (1, 4)
[[1]
 [2]
 [3]
 [4]] (4, 1)


**Indexing and slicing**

In [ ]:
# Slicing

arr = np.array([1,2,3,4])

print(arr[:2])
print(arr[2:])
print(arr[1:3])
print(arr[:-1])

[1 2]
[3 4]
[2 3]
[1 2 3]


In [ ]:
# Selecting values from array taht fulfill certain conditions

arr = np.arange(1, 13).reshape(3, 4)
print(arr)
print()

# Create a boolean mask to select certain values
print(arr > 6)
print()

print(arr[arr > 6])
print()

# And operations can be done with the & operator
print(arr[(arr>2) & (arr<10)])
print()

# Or operations can be done with the | operator
print(arr[(arr<5) | (arr==10)])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]

[ 7  8  9 10 11 12]

[3 4 5 6 7 8 9]

[ 1  2  3  4 10]


**How to create an array from existing data**

This section covers slicing and indexing, np.vstack(), np.hstack(), np.hsplit(), .view(), copy()

In [ ]:
# Stacking arrays

a = np.array([[1,1], [2,2]])
b = np.array([[3,3], [4,4]])


# Vertical stacking
print(np.vstack((a,b)))
print()

# Hozizontal stacking
print(np.hstack((a,b)))


[[1 1]
 [2 2]
 [3 3]
 [4 4]]

[[1 1 3 3]
 [2 2 4 4]]


In [ ]:
# Creating a View and Copy of an array

a = np.array([1,2,3,4])

# Copy
copy_a = a.copy()
copy_a[0] = 10
print(copy_a, a)
print()

# View (references the original array)
view_a = a.view()
view_a[0] = 10
print(view_a, a)

[10  2  3  4] [1 2 3 4]

[10  2  3  4] [10  2  3  4]


**Basic array operations**

This section covers addition, subtraction, multiplication, division, and more

In [ ]:
# Operations occur element wise

a = np.array([1, 2])
b = np.ones(2)

# Addition
print(a+b)
print()

# Subtraction
print(a-b)
print()

# Multiplication
print(a*b)
print()

# Division
print(a/b)


[2. 3.]

[0. 1.]

[1. 2.]

[1. 2.]


In [ ]:
# Sum of all elements in an array
a = np.arange(1, 5)
a.sum()

np.int64(10)

In [ ]:
# Sum of specific axis of array

b = a.reshape((2, 2))
print(b)
print()

# Rows
print(b.sum(axis=0))
print()

# Columns:
print(b.sum(axis=1))

[[1 2]
 [3 4]]

[4 6]

[3 7]


**Broadcasting**

Carrying out an operation between an array and a single number or between arrays of different sizes

In [ ]:
data = np.array([1,2])
print(data * 1.6)

[1.6 3.2]


**More useful array operations**

This section covers maximum, minimum, sum, mean, product, standard deviation, and more

In [ ]:
# Min, Max, Mean
# Can pass axis param into any of these to do for certain aix

a = np.arange(5)
print(a)
print()

# Min
print(a.min())
print()

# Max
print(a.max())
print()

# Mean
print(a.mean())

[0 1 2 3 4]

0

4

2.0


**Generating random numbers**


In [ ]:
rng = np.random.default_rng()

rng.integers(5, size=(2, 4))

array([[4, 1, 2, 1],
       [2, 2, 4, 0]])

**How to get unique items and counts**

This section covers np.unique()

In [6]:
# Finding Unique elements

a = np.array([1,1,2,3,4,4,5,6,7,8,8])

np.unique(a)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# Find Unique elements + indices + counts

np.unique(a, return_index=True, return_counts=True)

# Can be done for specific axis by passing in axis param

(array([1, 2, 3, 4, 5, 6, 7, 8]),
 array([0, 2, 3, 4, 6, 7, 8, 9]),
 array([2, 1, 1, 2, 1, 1, 1, 2]))

**Transposing and reshaping a matrix**

This section covers arr.reshape(), arr.transpose(), arr.T

In [13]:
# Transpose an array (reverse axis values (x, y) --> (y, x))

arr = np.arange(8).reshape((2, 4))
print(arr)
print()

print(arr.transpose())
print()

# or use

print(arr.T)

[[0 1 2 3]
 [4 5 6 7]]

[[0 4]
 [1 5]
 [2 6]
 [3 7]]

[[0 4]
 [1 5]
 [2 6]
 [3 7]]


**Reshaping and flattening multidimensional arrays**

This section covers .flatten(), ravel()

In [17]:
# ravel() returns a view while flatten() returns an object
# both return flattened versions of the array

a = np.arange(6).reshape((2, 3))
print(a)
print()

print(a.ravel())
print(a.flatten())

[[0 1 2]
 [3 4 5]]

[0 1 2 3 4 5]
[0 1 2 3 4 5]


**How to save and load NumPy objects**

This section covers np.save, np.savez, np.savetxt, np.load, np.loadtxt

In [ ]:
# Storing a single ndarray object with .save() that stores data, shape, dtype of array

a = np.arange(5)

# Saves it as a .npy file
np.save("single_save", a)

# Load the .npy file
b = np.load("single_save.npy")
print(b)

[0 1 2 3 4]


In [35]:
# Storing multiple ndarray object with .savez() that stores data, shape, dtype of array

a = np.arange(5)
b = np.arange(5, 10)

# Saves it as a .npz file
np.savez("multi_save", a=a, b=b)

# Load the .npy file
b = np.load("multi_save.npz")
print(b["a"], b["b"])

[0 1 2 3 4] [5 6 7 8 9]


In [41]:
# Basic version is storing numpy arrays as a plain text file like a .csv or .txt file using
# np.savetxt

a = np.arange(6)

np.savetxt("txt_save.csv", a)

txt = np.loadtxt("txt_save.csv")
print(txt)

[0. 1. 2. 3. 4. 5.]
